name: Deploy Insomnia Website
on:
  schedule:
    # Run at 0800 daily
    - cron: '0 8 * * *'
jobs:
  build:
    name: Trigger Netlify Build
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${TOKEN}
        env:
          TOKEN: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}
